### ISSUE TITLE
make page unresponsive

### ISSUE THREAD

**Issue by ag** [uxhell/phonenumber#1]
what do you think? i mean a _non responsive_ website is the **worst ux** ever, isn't it?

shouldn't we make our page unresponsive?

**Comment by ThisIsJeron** [comment]
@wongmjane says the page has to be functional, I suggested making the input options only one number but that's not functional.

**Comment by wongmjane** [comment]
It has to be extremely difficult and unfriendly to use, but not unusable

**Comment by thePsguy** [comment]
So, the UI can be nice, as long as the UX remains hell, right?

**Comment by vigzmv** [comment]
Satirical, hard to use and funny UX but it should be **usable** on all devices.

**Comment by thePsguy** [comment]
But bad UX can still look good, or not? I think the UI doesn't have to be bad to warrant a bad UX.

**Comment by wongmjane** [comment]
I wouldn't mind adding something into a good-looking UI that triggers graphic designers though (e.g. Comic Sans, slightly off kerning, slightly off alignment, etc)

**Comment by vigzmv** [comment]
A So good and beautiful UI with awful UX is also fun idea. :p
